id: 6c61b2fc6e6745b389be31278f254b54
initial_creation_type: ocr
source_metadata:
  volumes:
    2735118acfc240d59f3d50f261d2effc:
      base_file: v095.txt
      image_group_id: I1PD95941
      title: ''
      total_pages: 1144
      volume_number: 96
